# Generated by Django 5.1.1 on 2025-02-01 16:56

import django.core.validators
import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите полное имя сотрудника', max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('grade', models.CharField(blank=True, help_text='Например: 9А, 11Б', max_length=4, null=True, verbose_name='Класс')),
                ('personal_info', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('reprimands', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='myapp_cadet_full_na_443514_idx'), models.Index(fields=['birth_date'], name='myapp_cadet_birth_d_653596_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=10)),
                ('allowed_grades', models.CharField(blank=True, help_text='Классы, доступные для просмотра (через запятую)', max_length=255, null=True)),
                ('allowed_tables', models.CharField(blank=True, help_text='Доступные таблицы (cadets и/или employees)', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CadetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('file', models.FileField(storage=myapp.models.YandexS3Storage(), upload_to='cadet_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.cadet')),
            ],
            options={
                'unique_together': {('cadet', 'doc_type')},
            },
        ),
    ]
