# Generated by Django 5.1.1 on 2025-02-08 23:26

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_allowed_grades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email поддержки')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram поддержки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация о поддержке',
                'verbose_name_plural': 'Информация о поддержке',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cadetdocument',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cadetdocument',
            name='file',
            field=models.FileField(storage=myapp.models.YandexS3Storage(), upload_to='cadet_documents/%Y/%m/%d/'),
        ),
    ]
